services:
  db:
    image: postgres:16
    container_name: petstore-db
    environment:
      POSTGRES_DB: petstoredb
      POSTGRES_USER: petstoreadmin
      POSTGRES_PASSWORD: petstoreadmin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: petstore-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/petstoredb
      SPRING_DATASOURCE_USERNAME: petstoreadmin
      SPRING_DATASOURCE_PASSWORD: petstoreadmin
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: petstore-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: 